Repository KUSITMS-MOAMOA/MOAMOA_FE, pull requests merged in 2024-10, with the labels that each got.

#1 #0 [feat] : 초기세팅
  build.sh
Labels: ✨ feature

#2 #0 [feat] : main에 머지
  build.sh
Labels: ✨ feature

#3 Create main.yml
  .github/workflows/main.yml
Labels: ✨ feature

#4 #0 [chore] : 초기 세팅 실험
  src/App.tsx
Labels: ✨ feature

#6 #0 [feat] : axios 설치
  package-lock.json
  package.json
  src/App.tsx
Labels: ✨ feature

#8 [feat] : 폴더 구조, router 임시 생성
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/common/.keep
  src/components/common/button/Button.tsx
  src/components/common/input/Input.tsx
  src/components/common/modal/Modal.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/index.css
  src/pages/.keep
  src/pages/chatPage/ChatPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/oauthPage/OauthPage.tsx
  src/pages/skillArchivePage/SkillArchivePage.tsx
Labels: ✨ feature, 🐰 YEONA, 🐣 YUMIN

#9 #5 [feat] : color, font 설정
  package-lock.json
  package.json
  public/font/Pretendard-Bold.ttf
  public/font/Pretendard-Regular.ttf
  public/font/Pretendard-SemiBold.ttf
  src/App.tsx
  src/styles/global.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ✨ feature, 🐣 YUMIN

#12 #10 [feat] 공통 버튼 컴포넌트 생성
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/main.yml
  custom.d.ts
  public/icons/.keep
  public/icons/HamburgerIcon.svg
  public/icons/HomeIcon.svg
  public/icons/KeywordIcon.svg
  public/icons/MyIcon.svg
  public/icons/RecordIcon.svg
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonStyle.tsx
  src/pages/homePage/HomePage.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  tsconfig.app.json
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#13 #10 [feat] : 공통 input, selectBox 구현
  public/icons/DownArrowIcon.svg
  src/components/common/input/Input.tsx
  src/components/common/input/InputStyle.tsx
  src/components/common/selectbox/SelectBox.tsx
  src/components/common/selectbox/SelectBoxStyle.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#14 #10 [feat] : 공통 tabBar 생성
  public/icons/arrowIcon.svg
  public/icons/kebabIcon.svg
  src/components/common/selectbox/SelectBox.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/tabBar/TabBar.tsx
  src/components/layout/tabBar/TabBarStyle.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#15 #10 [feat] : 공통 chip, categoryChip 구현
  src/components/common/chip/CategoryChip.tsx
  src/components/common/chip/CategoryChipStyle.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/chip/ChipStyle.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#17 #16 [feat] : 홈페이지 UI 구현
  public/icons/ArrowIcon.svg
  public/icons/CirclesIcon.svg
  public/icons/KebabIcon.svg
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/features/home/List.tsx
  src/components/features/home/ListStyle.tsx
  src/components/layout/tabBar/TabBar.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/HomePageStyle.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#18 16 [feat] : 홈페이지 UI 구현
  index.html
  public/icons/BlueCirclesIcon.svg
  public/icons/CloseIcon.svg
  public/icons/YellowCirclesIcon.svg
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/BottomSheetStyle.tsx
  src/components/common/portal/Portal.tsx
  src/components/home/content/Content.tsx
  src/components/home/content/ContentStyle.tsx
  src/components/home/header/Header.tsx
  src/components/home/header/HeaderStyle.tsx
  src/components/home/list/List.tsx
  src/components/home/list/ListStyle.tsx
  src/components/home/sheetItem/SheetItem.tsx
  src/components/home/sheetItem/SheetItemStyle.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/homePage/HomePageStyle.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#22 [feat] : 메모 기록, 경험 기록에 사용되는 컴포넌트 생성
  public/icons/WhiteCirclesIcon.svg
  src/Router.tsx
  src/components/common/note/Note.tsx
  src/components/common/note/NoteStyle.tsx
  src/components/memo/Memo.tsx
  src/components/memo/MemoStyle.tsx
  src/components/record/Record.tsx
  src/components/record/RecordStyle.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordPage/RecordPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#20 [feat] 마이페이지 UI 구현
  public/icons/CheckIcon.svg
  public/icons/RightArrowIcon.svg
  src/Router.tsx
  src/components/common/bottomSheet/BottomSheetStyle.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/common/input/InputStyle.tsx
  src/components/common/modal/BasicModal.tsx
  src/components/common/modal/BasicModalStyle.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/common/modal/ConfirmModalStyle.tsx
  src/components/common/modal/DetailModal.tsx
  src/components/common/modal/DetailModalStyle.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalStyle.tsx
  src/components/common/selectbox/SelectBox.tsx
  src/components/common/selectbox/SelectBoxStyle.tsx
  src/components/editProfile/EditProfile.tsx
  src/components/editProfile/EditProfileStyle.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderStyle.tsx
  src/components/my/profile/Profile.tsx
  src/components/my/profile/ProfileStyle.tsx
  src/components/my/settings/SettingItem.tsx
  src/components/my/settings/SettingItemStyle.tsx
  src/components/my/settings/Settings.tsx
  src/components/my/settings/SettingsStyle.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/editProfile/EditProfilePageStyle.tsx
  src/pages/myPage/MyPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#23 #10 [feat] : Footer 구현
  custom.d.ts
  package-lock.json
  package.json
  public/icons/HamburgerIcon.svg
  public/icons/HomeIcon.svg
  public/icons/KeywordIcon.svg
  public/icons/MyIcon.svg
  src/App.css
  src/components/home/content/ContentStyle.tsx
  src/components/layout/footer/Footer.tsx
  src/components/layout/footer/FooterStyle.tsx
  src/index.css
  src/pages/homePage/HomePage.tsx
  src/pages/myPage/MyPage.tsx
  src/reset.css
  svg.d.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#25 #11 [feat] : 소셜 로그인 구현
  public/font/MontserratAlternates-Bold.ttf
  public/icons/KakaoIcon.svg
  src/Router.tsx
  src/api/Oauth.ts
  src/components/common/login/LoginButton.tsx
  src/main.tsx
  src/pages/loginPage/SigningIn.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPageStyle.tsx
  src/pages/oauthPage/OauthPage.tsx
  src/pages/oauthPage/OauthPageStyle.tsx
  src/pages/registerPage/SignUpPage.tsx
  src/pages/registerPage/SignUpPageStyle.tsx
  src/styles/global.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
  tsconfig.node.json
Labels: ⚙ api, 💄 ui, 🐣 YUMIN

#30 [feat] : 폴더 관리 페이지 UI 구현
  public/icons/DeleteIcon.svg
  public/icons/PlusIcon.svg
  src/Router.tsx
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/common/bottomSheet/FolderBottomSheetStyle.tsx
  src/components/common/modal/DetailModalStyle.tsx
  src/components/common/modal/ModalStyle.tsx
  src/components/folder/Folder.tsx
  src/components/folder/FolderStyle.tsx
  src/components/layout/header/HeaderStyle.tsx
  src/pages/editProfile/EditProfilePageStyle.tsx
  src/pages/folderPage/FolderPage.tsx
  src/pages/folderPage/FolderPageStyle.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/MyPageStyle.tsx
  tsconfig.app.json
Labels: ✨ feature, 💄 ui, 🐰 YEONA
