Repository KUSITMS-MOAMOA/MOAMOA_FE, pull requests merged in 2024-11, with the labels that each got.

#32 [feat] : 키워드 경험 페이지 UI 구현
  public/icons/ShortCirclesIcon.svg
  src/Router.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/common/chip/Chip.tsx
  src/components/common/chip/ChipStyle.tsx
  src/components/keyword/KeywordList.tsx
  src/components/keyword/KeywordListStyle.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/keywordPage/KeywordPageStyle.tsx
  src/styles/global.ts
Labels: 🔨 fix, ✨ feature, 💄 ui, 🐰 YEONA

#34 [feat] : 역량 레포트 페이지 UI 구현
  public/icons/ChangeFolderIcon.svg
  public/icons/EditIcon.svg
  public/icons/LeftCommentIcon.svg
  public/icons/ReportDeleteIcon.svg
  public/icons/RightCommentIcon.svg
  src/Router.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/BottomSheetStyle.tsx
  src/components/common/bottomSheet/EditBottomSheet.tsx
  src/components/common/bottomSheet/EditBottomSheetStyle.tsx
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/home/content/Content.tsx
  src/components/keyword/KeywordList.tsx
  src/components/layout/tabBar/TabBar.tsx
  src/components/list/content/Content.tsx
  src/components/report/comment/Comment.tsx
  src/components/report/comment/CommentStyle.tsx
  src/components/report/content/Content.tsx
  src/components/report/content/ContentStyle.tsx
  src/components/report/skill/Skill.tsx
  src/components/report/skill/SkillStyle.tsx
  src/pages/folderPage/FolderPage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#38 [refactor] : global font 적용
  public/font/.keep
  src/components/common/bottomSheet/BottomSheetStyle.tsx
  src/components/common/list/ListStyle.tsx
  src/components/common/modal/BasicModalStyle.tsx
  src/components/common/modal/DetailModalStyle.tsx
  src/components/editProfile/EditProfileStyle.tsx
  src/components/home/content/ContentStyle.tsx
  src/components/home/header/HeaderStyle.tsx
  src/components/home/sheetItem/SheetItemStyle.tsx
  src/components/layout/tabBar/TabBarStyle.tsx
  src/components/list/header/HeaderStyle.tsx
  src/components/my/profile/ProfileStyle.tsx
  src/components/my/settings/SettingsStyle.tsx
  src/components/report/content/ContentStyle.tsx
  src/pages/loginSuccessPage/LoginSuccessPageStyle.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/skillArchivePage/SkillArchivePage.tsx
Labels: 🛠 refactor, 🐰 YEONA

#37 [feat] : input 에러 처리 구현 및 적용
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/common/input/Input.tsx
  src/components/common/input/InputStyle.tsx
  src/components/editProfile/EditProfile.tsx
  src/hooks/.keep
  src/hooks/useNicknameValidation.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/registerPage/SignUpPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#43 [refactor] : header 크기 수정
  src/components/home/content/ContentStyle.tsx
  src/components/home/header/HeaderStyle.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/HeaderStyle.tsx
  src/components/layout/tabBar/TabBarStyle.tsx
  src/components/list/content/ContentStyle.tsx
  src/components/list/header/HeaderStyle.tsx
  src/components/report/content/ContentStyle.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/editProfile/EditProfilePageStyle.tsx
  src/pages/folderPage/FolderPage.tsx
  src/pages/folderPage/FolderPageStyle.tsx
  src/pages/keywordPage/KeywordPageStyle.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/MyPageStyle.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#45 #36 [feat] : 메모 기록 페이지 UI 구현
  src/components/common/button/ButtonStyle.tsx
  src/components/common/input/Input.tsx
  src/components/common/modal/ModalStyle.tsx
  src/components/layout/tabBar/TabBar.tsx
  src/components/layout/tabBar/TabBarStyle.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/memoPage/MemoPageStyle.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#46 #28 [feat] : 채팅 & 경험 기록 완료 페이지 UI 구현
  src/Router.tsx
  src/assets/icons/ChatProfileIcon.svg
  src/assets/icons/UpArrowIcon.svg
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatBoxStyle.tsx
  src/components/chat/ChatBubblStyle.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/GuideButton.tsx
  src/components/chat/GuideButtonStyle.tsx
  src/components/chat/ToastMessage.tsx
  src/components/chat/ToastMessageStyle.tsx
  src/components/common/modal/DetailModal.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/chatPage/ChatPageStyle.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/recordCompletePage/RecordCompletePageStyle.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#50 [refactor] 코드 리뷰 반영 리팩토링 2
  src/components/chat/ChatBox.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/utils/.keep
  src/utils/dateUtils.ts
Labels: 🛠 refactor

#53 [refactor] : 소셜 로그인 base URL을 환경 변수로 설정
  .gitignore
  src/api/Oauth.ts
Labels: 🛠 refactor, 🐣 YUMIN

#55 [refactor] : isClicked 사용
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🛠 refactor

#57 [hotfix] : vercel 404 오류
  vercel.json
Labels: 🔥 hot fix!!

#61 [refactor] : 마이 페이지 UI 수정 부분 반영 완료
  src/components/common/input/Input.Style.ts
  src/components/common/modal/DetailModal.Style.ts
  src/components/common/selectbox/SelectBox.Style.ts
  src/components/layout/tabBar/TabBar.Style.ts
  src/components/my/profile/Profile.Style.ts
  src/components/my/profile/Profile.tsx
  src/components/my/settings/SettingItem.Style.ts
  src/components/my/settings/Settings.Style.ts
  src/pages/editProfile/EditProfilePage.Style.ts
  src/pages/myPage/MyPage.Style.ts
  src/pages/myPage/MyPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#63 [feat] : 홈 페이지 UI 수정 반영
  public/images/.keep
  public/images/HeaderImage.png
  src/assets/icons/BlueCirclesIcon.svg
  src/assets/icons/CirclesIcon.svg
  src/assets/icons/HamburgerIcon.svg
  src/assets/icons/MenuIcon.svg
  src/assets/icons/YellowCirclesIcon.svg
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/RecordBottomSheet.Style.ts
  src/components/common/list/List.Style.ts
  src/components/common/list/List.tsx
  src/components/common/sideBar/SideBar.style.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/home/content/Content.Style.ts
  src/components/home/content/Content.tsx
  src/components/home/header/Header.Style.ts
  src/components/home/header/Header.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/home/sheetItem/SheetItem.tsx
  src/components/layout/header/Header.style.ts
  src/components/layout/header/Header.tsx
  src/components/list/content/Content.tsx
  src/pages/homePage/HomePage.tsx
Labels: 💄 ui, 🐰 YEONA

#68 [chore] : localhost HTTPS 설정
  .gitignore
  package-lock.json
  package.json
  vite.config.ts
Labels: 🐣 YUMIN, 💡chore

#66 [feat] : 폴더 페이지 UI 수정 반영
  src/components/common/bottomSheet/BottomSheet.Style.ts
  src/components/common/bottomSheet/FolderBottomSheet.Style.ts
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/layout/tabBar/TabBar.Style.ts
  src/pages/folderPage/FolderPage.Style.ts
  src/pages/folderPage/FolderPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 💄 ui, 🐰 YEONA

#70 [feat] : 마이 페이지 사이드바 적용
  src/components/layout/header/Header.style.ts
  src/components/layout/header/Header.tsx
  src/components/my/profile/Profile.tsx
  src/pages/myPage/MyPage.Style.ts
  src/pages/myPage/MyPage.tsx
Labels: 💄 ui, 🐰 YEONA

#71 [feat] : 경험 리스트 페이지 UI 수정 반영
  src/components/common/chip/CategoryChip.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/list/content/Content.Style.ts
  src/components/list/content/Content.tsx
  src/components/list/header/Header.Style.ts
  src/components/list/header/Header.tsx
  src/pages/listPage/ListPage.Style.ts
  src/pages/listPage/ListPage.tsx
  src/pages/myPage/MyPage.Style.ts
Labels: 💄 ui, 🐰 YEONA

#74 #72 [feat] : 키워드 페이지 UI 수정 반영
  src/assets/icons/ShortCirclesIcon.svg
  src/components/common/empty/Empty.style.ts
  src/components/common/empty/Empty.tsx
  src/components/keyword/KeywordList.Style.ts
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/keyword/keywordList/KeywordList.tsx
  src/components/keyword/keywordSkill/KeywordSkill.style.ts
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/list/content/Content.Style.ts
  src/components/list/content/Content.tsx
  src/pages/keywordPage/KeywordPage.tsx
Labels: 💄 ui, 🐰 YEONA

#76 #75 [feat] : 역량 모아보기 페이지 UI 수정 반영
  src/assets/icons/EditIcon.svg
  src/assets/icons/LeftCommentIcon.svg
  src/assets/icons/RightCommentIcon.svg
  src/components/common/bottomSheet/EditBottomSheet.Style.ts
  src/components/common/bottomSheet/EditBottomSheet.tsx
  src/components/common/button/Button.Style.ts
  src/components/common/button/Button.tsx
  src/components/layout/tabBar/TabBar.Style.ts
  src/components/layout/tabBar/TabBar.tsx
  src/components/report/comment/Comment.Style.ts
  src/components/report/comment/Comment.tsx
  src/components/report/content/Content.Style.ts
  src/components/report/content/Content.tsx
  src/components/report/skill/Skill.Style.ts
  src/components/report/skill/Skill.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 💄 ui, 🐰 YEONA

#78 [refactor] : Floating 버튼 공통 컴포넌트로 분리
  src/components/common/button/FloatingButton.Style.ts
  src/components/common/button/FloatingButton.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/listPage/ListPage.Style.ts
  src/pages/listPage/ListPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#80 [refactor] : BottomSheet 수정
  src/components/common/bottomSheet/BottomSheet.Style.ts
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/EditBottomSheet.Style.ts
  src/components/common/bottomSheet/EditBottomSheet.tsx
  src/components/common/bottomSheet/FolderBottomSheet.Style.ts
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/common/bottomSheet/RecordBottomSheet.Style.ts
  src/components/common/bottomSheet/RecordBottomSheet.tsx
Labels: 🛠 refactor, 🐰 YEONA

#83 [feat] : 역량 모아보기 편집 바텀시트 구현
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/Textarea.Style.ts
  src/components/common/bottomSheet/reportBottomSheet/Textarea.tsx
  src/components/layout/tabBar/TabBar.tsx
  src/components/report/content/Content.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#84 #82 [feat] : 메모 기록 페이지 UI 수정 반영
  src/components/common/selectbox/SelectBox.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: 💄 ui, 🐣 YUMIN

#88 [chore] : 배포 환경을 위한 vite.config.js 수정
  vite.config.ts
Labels: 🔨 fix, 🐰 YEONA

#89 [fix] : yml 파일 수정
  .github/workflows/main.yml
Labels: 🔨 fix, 🐰 YEONA

#91 [fix] : build 파일 수정
  .github/workflows/main.yml
  build.sh
Labels: 🔨 fix, 🐰 YEONA

#93 #92 [refactor] : 탭바 수정
  index.html
  src/components/layout/tabBar/TabBar.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#94 #92 [refactor] : background, box-shadow 변경
  src/components/folder/Folder.Style.ts
  src/components/list/header/Header.Style.ts
  src/pages/folderPage/FolderPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#95 #92 [refactor] : 아이콘 수정
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: 🛠 refactor, 🐰 YEONA

#96 #39 [feat] : 홈 페이지 API 연동
  src/api/Home.ts
  src/components/home/content/Content.tsx
  vite.config.ts
Labels: ✨ feature, ⚙ api, 🐰 YEONA

#97 #92 [refactor] : 스텝업데이 수정 사항 반영
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/LodingDot.Style.ts
  src/components/chat/LodingDots.tsx
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
  src/components/editProfile/EditProfile.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA, 🐣 YUMIN

#100 Feat/home
  src/api/Folder.ts
  src/api/Home.ts
  src/components/home/content/Content.tsx
  vite.config.ts
Labels: 🔨 fix, ⚙ api, 🐰 YEONA

#99 #98 [feat] : 역량 그래프 UI 구현
  package-lock.json
  package.json
  src/components/report/skill/SkillData.ts
  src/components/report/skill/SkillGraph.Style.ts
  src/components/report/skill/SkillGraph.tsx
  src/components/report/skill/SkillList.Style.ts
  src/components/report/skill/SkillList.tsx
  src/pages/keywordPage/KeywordPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#101 [refactor] : 홈 페이지 API 연동 refactor
  src/api/Home.ts
Labels: 🛠 refactor, ⚙ api, 🐰 YEONA

#102 [feat] : 마이페이지 API 연동
  src/api/My.ts
  src/components/common/modal/ConfirmModal.tsx
  src/components/my/profile/Profile.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/myPage/MyPage.tsx
Labels: ✨ feature, ⚙ api, 🐰 YEONA

#104 #11 [feat] : 1.3 액세스 토큰 재발급 요청 인터셉터 처리
  src/api/Oauth.ts
  src/api/instance.ts
Labels: ✨ feature, ⚙ api, 🐣 YUMIN

#105 [feat] : 폴더별 경험 조회 API 연동
  src/api/Folder.ts
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/list/content/Content.tsx
  src/components/list/header/Header.tsx
  src/pages/folderPage/FolderPage.Style.ts
  src/pages/folderPage/FolderPage.tsx
  src/pages/listPage/ListPage.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
  src/types/Folder.ts
Labels: ✨ feature, ⚙ api, 🐰 YEONA

#107 [feat] : 폴더별 리스트 조회 무한 스크롤 구현 완료
  src/api/Folder.ts
  src/components/list/content/Content.Style.ts
  src/components/list/content/Content.tsx
  src/pages/listPage/ListPage.Style.ts
  src/pages/listPage/ListPage.tsx
Labels: ✨ feature, 🐰 YEONA

#109 [feat] : 역량 분석 쪽 API 연동 완료 !!!!!!
  src/api/Analysis.ts
  src/components/common/bottomSheet/FolderBottomSheet.tsx
  src/components/common/bottomSheet/FolderChangeBottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.Style.ts
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/Textarea.Style.ts
  src/components/common/selectbox/SelectBox.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/report/content/Content.tsx
  src/pages/folderPage/FolderPage.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
  src/types/Analysis.ts
Labels: ✨ feature, ⚙ api, 🐰 YEONA

#111 [feat] : UX writing 및 UI 수정 반영
  src/Router.tsx
  src/assets/icons/FolderIcon.svg
  src/components/common/bottomSheet/EditBottomSheet.tsx
  src/components/common/bottomSheet/FolderChangeBottomSheet.tsx
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/ReportBottomSheet.tsx
  src/components/common/bottomSheet/reportBottomSheet/Textarea.Style.ts
  src/components/common/chip/CategoryChip.Style.ts
  src/components/common/selectbox/SelectBox.tsx
  src/components/common/sideBar/SideBar.tsx
  src/components/editProfile/EditProfile.tsx
  src/components/home/content/Content.tsx
  src/components/home/header/Header.Style.ts
  src/components/home/header/Header.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/keyword/keywordSkill/KeywordSkill.style.ts
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/list/header/Header.tsx
  src/components/my/profile/Profile.tsx
  src/components/my/settings/SettingItem.Style.ts
  src/components/my/settings/SettingItem.tsx
  src/components/my/settings/Settings.tsx
  src/components/report/comment/Comment.tsx
  src/components/report/content/Content.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/folderPage/FolderPage.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/listPage/ListPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/recordPage/RecordPage.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#113 [feat] : 닉네임 로컬스토리지 저장 후 적용
  src/App.tsx
  src/api/Home.ts
  src/api/instance.ts
  src/components/common/modal/BasicModal.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/home/header/Header.tsx
  src/components/keyword/header/KeywordHeader.tsx
  src/components/list/header/Header.tsx
  src/components/report/content/Content.tsx
  src/pages/listPage/ListPage.tsx
  src/pages/loginPage/SigningIn.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/registerPage/SignUpPage.tsx
Labels: ✨ feature, 🐰 YEONA

#115 [feat] : MOAMOA로 변경
  .github/workflows/main.yml
  build.sh
Labels: ✨ feature

#118 [feat] : 플로팅 버튼 수정 및 채팅 다시보기 페이지 이동 수정
  src/Router.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/list/content/Content.tsx
  src/components/report/content/Content.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/listPage/ListPage.tsx
Labels: ✨ feature, 🐰 YEONA

#119 #52 [feat] : 채팅 페이지 1차 api 연동
  src/Router.tsx
  src/api/Chat.ts
  src/api/Graph.ts
  src/components/chat/ChatBubble.tsx
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/home/sheetItem/SheetItem.tsx
  src/components/report/skill/SkillData.ts
  src/components/report/skill/SkillGraph.tsx
  src/components/report/skill/SkillList.Style.ts
  src/components/report/skill/SkillList.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/types/SkillData.ts
Labels: ✨ feature, ⚙ api, 🐣 YUMIN

#123 #51 [feat] : 메모 페이지 api 연동
  src/Router.tsx
  src/api/Memo.ts
  src/components/report/content/Content.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: ✨ feature, ⚙ api, 🐣 YUMIN

#125 [feat] : PC 버전 SideBar 및 홈페이지 UI 구현
  src/App.Style.ts
  src/App.tsx
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/button/FloatingButton.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/list/List.Style.ts
  src/components/common/sideBar/SideBar.style.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarItem.tsx
  src/components/home/content/Content.Style.ts
  src/components/home/content/Content.tsx
  src/components/home/header/Header.Style.ts
  src/components/home/header/Header.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/home/sheetItem/SheetItem.tsx
  src/components/layout/header/Header.style.ts
  src/pages/homePage/HomePage.Style.ts
  src/pages/homePage/HomePage.tsx
  src/styles/theme.ts
Labels: 💄 ui, 🐰 YEONA

#127 #52 [feat] : 채팅 페이지 api 연동 완료
  src/api/Chat.ts
  src/api/Graph.ts
  src/api/Memo.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/oauthPage/OauthPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: ✨ feature, ⚙ api, 🐣 YUMIN

#128 [feat] : 2차 API 연동 후 배포
  src/App.Style.ts
  src/App.tsx
  src/Router.tsx
  src/api/Chat.ts
  src/api/Graph.ts
  src/api/Memo.ts
  src/components/chat/ChatBubble.tsx
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/button/FloatingButton.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/list/List.Style.ts
  src/components/common/sideBar/SideBar.style.ts
  src/components/common/sideBar/SideBar.tsx
  src/components/common/sideBar/SideBarItem.tsx
  src/components/home/content/Content.Style.ts
  src/components/home/content/Content.tsx
  src/components/home/header/Header.Style.ts
  src/components/home/header/Header.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/home/sheetItem/SheetItem.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/layout/header/Header.style.ts
  src/components/list/content/Content.tsx
  src/components/report/content/Content.tsx
  src/components/report/skill/SkillData.ts
  src/components/report/skill/SkillGraph.tsx
  src/components/report/skill/SkillList.Style.ts
  src/components/report/skill/SkillList.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/homePage/HomePage.Style.ts
  src/pages/homePage/HomePage.tsx
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/listPage/ListPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/oauthPage/OauthPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/styles/theme.ts
  src/types/SkillData.ts
Labels: ✨ feature, ⚙ api, 💄 ui, 🐰 YEONA, 🐣 YUMIN

#130 [feat] : 마이페이지, 프로필 페이지 PC ver UI 구현
  src/components/common/input/Input.Style.ts
  src/components/common/list/List.Style.ts
  src/components/common/selectbox/SelectBox.Style.ts
  src/components/editProfile/EditProfile.Style.ts
  src/components/home/content/Content.Style.ts
  src/components/layout/header/Header.style.ts
  src/components/my/profile/Profile.Style.ts
  src/components/my/profile/Profile.tsx
  src/components/my/settings/SettingItem.Style.ts
  src/components/my/settings/SettingItem.tsx
  src/components/my/settings/Settings.Style.ts
  src/pages/editProfile/EditProfilePage.Style.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/myPage/MyPage.Style.ts
  src/pages/myPage/MyPage.tsx
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#132 [feat] : 폴더 관리 페이지 PC ver UI 구현
  src/components/common/modal/Modal.Style.ts
  src/components/common/modal/Modal.tsx
  src/components/common/popup/FolderPopUp.Style.ts
  src/components/common/popup/FolderPopUp.tsx
  src/components/list/content/Content.tsx
  src/components/list/header/Header.Style.ts
  src/components/list/header/Header.tsx
  src/hooks/useMediaQuery.ts
  src/pages/folderPage/FolderPage.Style.ts
  src/pages/folderPage/FolderPage.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🔨 fix, ✨ feature, 💄 ui, 🐰 YEONA

#134 #129 [refactor] : 1차 QA 수정 사항 일부 반영
  public/font/MontserratAlternates-Bold.ttf
  public/font/MontserratAlternates-Bold.woff
  src/api/Chat.ts
  src/components/report/skill/SkillGraph.Style.ts
  src/components/report/skill/SkillGraph.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.Style.ts
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/oauthPage/OauthPage.Style.ts
  src/pages/registerPage/SignUpPage.tsx
  src/styles/global.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: 🔨 fix, 🛠 refactor, 🐣 YUMIN

#136 [feat] : 경험 모아보기 페이지 PC ver UI 구현 완료
  src/components/list/header/Header.Style.ts
  src/pages/listPage/ListPage.Style.ts
  src/pages/listPage/ListPage.tsx
Labels: 💄 ui, 🐰 YEONA

#138 [feat] : 사이드 바 호버 했을 때 색깔 변화 및 애니메이션 추가, 닉네임 수정
  src/components/common/sideBar/SideBar.style.ts
  src/components/common/sideBar/SideBarItem.tsx
  src/hooks/useNicknameValidation.ts
  src/pages/registerPage/SignUpPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#140 #129 [refactor] : QA 수정 사항 일부 반영 2
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: 🔨 fix, 🛠 refactor, 🐣 YUMIN

#141 [feat] : 역량 모아보기 키워드 페이지 PC ver UI 구현
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/keyword/keywordSkill/KeywordSkill.style.ts
  src/components/keyword/skill/SkillGraph.Style.ts
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.Style.ts
  src/components/keyword/skill/SkillList.tsx
  src/components/report/content/Content.tsx
  src/pages/keywordPage/KeywordPage.tsx
Labels: 💄 ui, 🐰 YEONA

#143 [fix] : 제목이 매우 긴 경우 처리
  src/components/common/list/List.Style.ts
  src/components/keyword/keywordList/KeywordList.Style.ts
Labels: 🔨 fix, 💄 ui, 🐰 YEONA

#148 [refactor] : 리스트의 max-width 너비 고정
  src/components/common/list/List.Style.ts
  src/components/keyword/keywordList/KeywordList.Style.ts
Labels: 🛠 refactor, 💄 ui, 🐰 YEONA

#150 [fix] : 1차 QA 수정 요구 사항 반영
  index.html
  src/components/common/popup/FolderChangePopUp.tsx
  src/pages/reportPage/ReportPage.tsx
  src/types/Analysis.ts
Labels: 🔨 fix, ✨ feature, ⚙ api, 🐰 YEONA

#152 [feat] : 토스트 애니메이션 수정 및 적용
  src/components/chat/ToastMessage.Style.ts
  src/components/common/popup/FolderChangePopUp.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 🔨 fix, ✨ feature, 💄 ui, 🐰 YEONA

#153 [refactor] : 채팅/메모 다시보기 시 여러 기능 비활성화 & api 재요청
  src/api/Chat.ts
  src/components/chat/ChatBox.tsx
  src/pages/chatPage/ChatPage.Style.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🛠 refactor, 💄 ui, 🐣 YUMIN

#154 [feat] : 로딩 화면 구현
  src/assets/icons/LoadingSpinner.gif
  src/components/chat/ChatBubble.Style.ts
  src/components/common/loading/LoadingScreen.Style.ts
  src/components/common/loading/LoadingScreen.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/loginPage/SigningIn.tsx
  src/pages/memoPage/MemoPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#157 [feat] : 로그인 & 채팅 페이지 PC UI 구현
  public/images/LogoImage.png
  src/App.tsx
  src/assets/icons/ChatProfileIcon.svg
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatBubble.Style.ts
  src/components/chat/ChatBubble.tsx
  src/pages/chatPage/ChatPage.Style.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.Style.ts
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/oauthPage/OauthPage.Style.ts
  src/pages/oauthPage/OauthPage.tsx
  src/pages/registerPage/SignUpPage.Style.ts
  src/pages/registerPage/SignUpPage.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#158 [feat] : 메모 & 경험 기록 완료 페이지 PC UI
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: ✨ feature, 💄 ui, 🐣 YUMIN

#161 [refactor] : 역량 그래프 & 리스트 정렬 수정
  src/components/keyword/skill/SkillGraph.Style.ts
  src/components/keyword/skill/SkillList.Style.ts
Labels: 🛠 refactor, 🐣 YUMIN

#164 [feat] : 온보딩 페이지 구현 및 적용
  public/images/OnBoarding1.png
  public/images/OnBoarding2.png
  public/images/OnBoarding3.png
  public/images/OnBoarding4.png
  src/Router.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/onboardingPage/OnboardingPage.Style.ts
  src/pages/onboardingPage/OnboardingPage.tsx
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#166 [fix] : 2차 QA 수정 요청 사항 반영 - 연아
  public/font/MontserratAlternates-ExtraBold.woff
  src/components/common/list/List.Style.ts
  src/components/common/popup/reportPopup/ReportPopUp.Style.ts
  src/components/common/popup/reportPopup/ReportPopUp.tsx
  src/components/common/popup/reportPopup/Textarea.Style.ts
  src/components/common/sideBar/SideBar.style.ts
  src/components/common/sideBar/SideBarItem.tsx
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/layout/footer/Footer.Style.ts
  src/components/layout/footer/Footer.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/homePage/HomePage.Style.ts
  src/pages/listPage/ListPage.Style.ts
  src/pages/reportPage/ReportPage.tsx
  src/styles/global.ts
Labels: 🐞 bug, 🔨 fix, 🐰 YEONA

#168 [feat] : 그래픽 아이콘들 추가
  public/images/EmptyImage.png
  public/images/ProfileImage.png
  src/assets/icons/ChatIcon.svg
  src/assets/icons/MemoIcon.svg
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/empty/Empty.style.ts
  src/components/common/empty/Empty.tsx
  src/components/common/popup/EditPopUp.tsx
  src/components/common/popup/FolderChangePopUp.tsx
  src/components/common/popup/FolderPopUp.tsx
  src/components/common/popup/reportPopup/ReportPopUp.tsx
  src/components/home/header/Header.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/home/sheetItem/SheetItem.tsx
  src/components/my/profile/Profile.Style.ts
  src/components/my/profile/Profile.tsx
  src/components/report/comment/Comment.Style.ts
  src/components/report/comment/Comment.tsx
Labels: 💄 ui, 🐰 YEONA

#171 [fix] : 동적 라우트에 대한 SideBar 표시 로직 수정
  src/App.tsx
Labels: 🔨 fix, 🛠 refactor, 🐣 YUMIN

#173 [fix] : 2차 QA 수정 요청 사항 반영
  src/api/Graph.ts
  src/assets/icons/ChatProfileIcon.svg
  src/assets/icons/MemoPageIcon.png
  src/components/chat/ChatBubble.Style.ts
  src/components/common/loading/LoadingScreen.tsx
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.tsx
  src/components/memo/Memo.Style.ts
  src/components/memo/Memo.tsx
  src/components/record/Record.Style.ts
  src/components/record/Record.tsx
  src/pages/chatPage/ChatPage.Style.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🔨 fix, 🛠 refactor, 💄 ui, 🐣 YUMIN

#175 [refactor] : 아이콘 수정 및 배경화면 적용
  public/images/HomeImage.png
  src/assets/icons/KeywordIcon.svg
  src/assets/icons/MenuIcon.svg
  src/components/chat/ChatBubble.Style.ts
  src/components/home/header/Header.Style.ts
Labels: 🛠 refactor, 🐰 YEONA

#178 [fix] : 3차 QA 수정 사항 반영
  public/images/MemoHeaderImage.png
  src/api/Record.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: 🐞 bug, 🔨 fix, 🛠 refactor, 🐣 YUMIN

#180 [fix] 3차 QA 수정 요청 사항 반영 - 연아
  public/images/ChatImg.png
  public/images/MemoImg.png
  src/assets/icons/ChatIcon.svg
  src/assets/icons/MemoIcon.svg
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/list/List.Style.ts
  src/components/common/modal/Modal.Style.ts
  src/components/common/popup/EditPopUp.Style.ts
  src/components/common/popup/EditPopUp.tsx
  src/components/common/popup/FolderChangePopUp.tsx
  src/components/common/popup/FolderPopUp.tsx
  src/components/common/popup/reportPopup/ReportPopUp.Style.ts
  src/components/common/sideBar/SideBar.style.ts
  src/components/editProfile/EditProfile.tsx
  src/components/home/content/Content.Style.ts
  src/components/home/header/Header.tsx
  src/components/my/profile/Profile.Style.ts
  src/components/my/settings/SettingItem.Style.ts
  src/components/report/content/Content.Style.ts
  src/pages/editProfile/EditProfilePage.Style.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/folderPage/FolderPage.Style.ts
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/myPage/MyPage.Style.ts
  src/pages/reportPage/ReportPage.Style.ts
  src/pages/reportPage/ReportPage.tsx
Labels: 🐞 bug, 🔨 fix, 🛠 refactor, 🐰 YEONA

#181 [fix] : 3차 QA 수정 사항 반영 - 유민
  public/images/HeaderImage.png
  public/images/NotFoundImage.png
  src/App.tsx
  src/Router.tsx
  src/components/common/loading/LoadingScreen.tsx
  src/components/keyword/skill/SkillGraph.Style.ts
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.Style.ts
  src/components/keyword/skill/SkillList.tsx
  src/hooks/useNicknameValidation.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/keywordPage/KeywordPage.Style.ts
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/notFoundPage/NotFoundPage.Style.ts
  src/pages/notFoundPage/NotFoundPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.tsx
Labels: 🐞 bug, 🔨 fix, 🛠 refactor, 🐣 YUMIN

#182 [fix] : QA 수정 요구 사항 반영 후 배포
  public/images/ChatImg.png
  public/images/HeaderImage.png
  public/images/MemoHeaderImage.png
  public/images/MemoImg.png
  public/images/NotFoundImage.png
  src/App.tsx
  src/Router.tsx
  src/api/Record.ts
  src/assets/icons/ChatIcon.svg
  src/assets/icons/MemoIcon.svg
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/list/List.Style.ts
  src/components/common/loading/LoadingScreen.tsx
  src/components/common/modal/Modal.Style.ts
  src/components/common/popup/EditPopUp.Style.ts
  src/components/common/popup/EditPopUp.tsx
  src/components/common/popup/FolderChangePopUp.tsx
  src/components/common/popup/FolderPopUp.tsx
  src/components/common/popup/reportPopup/ReportPopUp.Style.ts
  src/components/common/sideBar/SideBar.style.ts
  src/components/editProfile/EditProfile.tsx
  src/components/home/content/Content.Style.ts
  src/components/home/header/Header.tsx
  src/components/keyword/skill/SkillGraph.Style.ts
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.Style.ts
  src/components/keyword/skill/SkillList.tsx
  src/components/my/profile/Profile.Style.ts
  src/components/my/settings/SettingItem.Style.ts
  src/components/report/content/Content.Style.ts
  src/hooks/useNicknameValidation.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/editProfile/EditProfilePage.Style.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/folderPage/FolderPage.Style.ts
  src/pages/keywordPage/KeywordPage.Style.ts
  src/pages/keywordPage/KeywordPage.tsx
  src/pages/loginSuccessPage/LoginSuccessPage.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/myPage/MyPage.Style.ts
  src/pages/notFoundPage/NotFoundPage.Style.ts
  src/pages/notFoundPage/NotFoundPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.Style.ts
  src/pages/reportPage/ReportPage.tsx
Labels: 🐞 bug, 🔨 fix, 🛠 refactor, 🐰 YEONA, 🐣 YUMIN

#183 #177 [fix] : 채팅 input 폰트 사이즈 수정
  src/components/chat/ChatBox.Style.ts
Labels: 🔨 fix, 🛠 refactor, 🐣 YUMIN

#184 [fix] : input 폰트 사이즈 수정
  src/components/chat/ChatBox.Style.ts
Labels: 🔨 fix, 🐣 YUMIN

#185 [fix] : QA 수정 요청 사항 반영
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/list/header/Header.Style.ts
  src/components/my/profile/Profile.Style.ts
  src/components/report/content/Content.Style.ts
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/myPage/MyPage.Style.ts
Labels: 🐞 bug, 💄 ui, 🐰 YEONA

#186 [fix] : QA 수정 요청 사항 반영
  src/App.tsx
  src/Router.tsx
  src/assets/icons/AddFolderIcon.svg
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.Style.ts
  src/components/keyword/skill/SkillList.tsx
  src/hooks/useValidatePathId.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/keywordPage/KeywordPage.Style.ts
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/registerPage/SignUpPage.Style.ts
  src/pages/reportPage/ReportPage.tsx
Labels: 🔨 fix, ✨ feature, ⚙ api, 🐣 YUMIN

#187 [fix] : 자잘한 스타일 수정
  src/components/common/sideBar/SideBarItem.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
Labels: 🔨 fix, 💄 ui

#188 [fix] : QA 수정 요청 사항 반영
  src/App.tsx
  src/Router.tsx
  src/assets/icons/AddFolderIcon.svg
  src/components/common/sideBar/SideBarItem.tsx
  src/components/home/sheetItem/SheetItem.Style.ts
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.Style.ts
  src/components/keyword/skill/SkillList.tsx
  src/components/list/header/Header.Style.ts
  src/components/my/profile/Profile.Style.ts
  src/components/report/content/Content.Style.ts
  src/hooks/useValidatePathId.ts
  src/pages/chatPage/ChatPage.tsx
  src/pages/editProfile/EditProfilePage.tsx
  src/pages/keywordPage/KeywordPage.Style.ts
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
  src/pages/myPage/MyPage.Style.ts
  src/pages/recordCompletePage/RecordCompletePage.Style.ts
  src/pages/registerPage/SignUpPage.Style.ts
  src/pages/reportPage/ReportPage.tsx
Labels: 🐞 bug, 🔨 fix, 💄 ui, 🐰 YEONA, 🐣 YUMIN

#190 [fix] : 자잘한 스타일 수정 후 배포
  src/components/my/settings/Settings.tsx
  src/pages/onboardingPage/OnboardingPage.Style.ts
Labels: 🔨 fix, 🐰 YEONA

#191 #179 [fix] : 온보딩 페이지 수정
  src/pages/onboardingPage/OnboardingPage.Style.ts
  src/pages/onboardingPage/OnboardingPage.tsx
Labels: 🔨 fix, 💄 ui

#192 [fix] : 온보딩 페이지 이동 수정
  src/pages/onboardingPage/OnboardingPage.Style.ts
  src/pages/onboardingPage/OnboardingPage.tsx
Labels: 🔨 fix, 🐰 YEONA

#193 [fix] : 자잘한 스타일 수정
  src/pages/loginSuccessPage/LoginSuccessPage.Style.ts
  src/pages/registerPage/SignUpPage.Style.ts
Labels: 🛠 refactor, 💄 ui, 🐣 YUMIN
