Repository KUSITMS-MOAMOA/MOAMOA_FE, pull requests merged in 2025-03, with the labels that each got.

#228 [fix] : 채팅 임시 저장 시 기존 채팅방 삭제 로직 수정
  src/api/Chat.ts
  src/pages/chatPage/ChatPage.tsx
Labels: 🐞 bug, 🔨 fix, 🐣 YUMIN

#229 [fix] : 채팅 임시 저장 시 기존 채팅방 삭제 로직 수정
  src/api/Chat.ts
  src/pages/chatPage/ChatPage.tsx
Labels: 🐞 bug, 🔨 fix, 🐣 YUMIN

#230 [feat] : 채팅 입력창 동적 높이 조절 기능 추가
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: ✨ feature, 🛠 refactor, 🐣 YUMIN

#231 [feat] : 채팅 입력창 동적 높이 조절 기능 추가
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/pages/memoPage/MemoPage.Style.ts
  src/pages/memoPage/MemoPage.tsx
Labels: ✨ feature, 🛠 refactor, 🐣 YUMIN

#232 [feat] : PWA 자동 업데이트 기능 추가 & IOS 하단 여백 제거
  public/service-worker.js
  src/serviceWorkerRegistration.ts
  src/styles/global.ts
  vite.config.ts
Labels: ✨ feature, 🛠 refactor, 🐣 YUMIN

#233 [feat] : PWA 자동 업데이트 기능 추가 & IOS 하단 여백 제거
  public/service-worker.js
  src/serviceWorkerRegistration.ts
  src/styles/global.ts
  vite.config.ts
Labels: ✨ feature, 🛠 refactor, 🐣 YUMIN

#235 [feat] : 아이콘 추가
  src/assets/icons/KeywordPageIcon.svg
  src/assets/icons/ListPageIcon.svg
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/header/KeywordHeader.tsx
  src/components/list/header/Header.Style.ts
  src/components/list/header/Header.tsx
Labels: 💄 ui, 🐰 YEONA

#238 [fix] : handleSend 중복 실행 방지 및 메시지 초기화 문제 해결
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
Labels: 🔨 fix, 🐣 YUMIN

#239 [fix] : handleSend 중복 실행 방지 및 메시지 초기화 문제 해결
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
Labels: 🔨 fix, 🐣 YUMIN

#240 fix: 아이폰에서 줄바꿈 안 되는 문제 해결
  src/components/chat/ChatBox.tsx
Labels: 🔨 fix, 🐣 YUMIN

#241 [fix] : PC 엔터 전송 안 되는 문제 해결
  src/components/chat/ChatBox.tsx
Labels: 🔨 fix, 🐣 YUMIN

#242 [style] : 로그인 화면 드롭다운 가리는 문제 해결
  src/pages/registerPage/SignUpPage.Style.ts
Labels: 🔨 fix, 🐣 YUMIN

#243 Develop
  index.html
  src/pages/registerPage/SignUpPage.tsx
Labels: ✨ feature, 🐣 YUMIN

#246 [refactor] : SkillGraph와 SkillList에서 getGraph 중복 호출 제거
  src/components/keyword/skill/SkillGraph.tsx
  src/components/keyword/skill/SkillList.tsx
  src/pages/keywordPage/KeywordPage.tsx
Labels: 🛠 refactor, 🐣 YUMIN

#247 [refactor] : iOS PWA 전체화면 지원을 위한 viewport-fit=cover 적용
  index.html
  src/components/chat/ChatBox.Style.ts
  src/styles/global.ts
Labels: 🛠 refactor, 🐣 YUMIN

#248 [revert] : iOS PWA 전체화면 지원을 위한 viewport-fit=cover 적용 롤백
  index.html
Labels: 🐞 bug, 🐣 YUMIN
