Repository KUSITMS-MOAMOA/MOAMOA_FE, pull requests merged in 2025-01, with the labels that each got.

#195 [refactor] : 자잘한 코드 스타일 수정
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/FloatingButton.Style.ts
  src/components/common/modal/ConfirmModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/popup/EditPopUp.Style.ts
  src/components/common/popup/EditPopUp.tsx
  src/components/common/popup/reportPopup/ReportPopUp.tsx
  src/components/editProfile/EditProfile.tsx
  src/components/folder/Folder.tsx
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/keyword/skill/SkillList.tsx
  src/components/list/content/Content.tsx
  src/components/report/comment/Comment.tsx
  src/components/report/skill/Skill.tsx
Labels: 🛠 refactor, 🐰 YEONA

#197 [refactor] : jsDocs 추가 및 css 수정
  index.html
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/GuideButton.Style.ts
Labels: 🛠 refactor, 🐣 YUMIN

#199 [feat] : msclarity 코드 삽입
  index.html
Labels: 📄 docs, 🐰 YEONA

#200 [feat] : 자잘한 코드 수정 및 msclarity 코드 삽입
  index.html
  src/components/chat/ChatBox.Style.ts
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatBubble.tsx
  src/components/chat/GuideButton.Style.ts
  src/components/common/bottomSheet/RecordBottomSheet.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/FloatingButton.Style.ts
  src/components/common/modal/ConfirmModal.tsx
  src/components/common/modal/Modal.tsx
  src/components/common/popup/EditPopUp.Style.ts
  src/components/common/popup/EditPopUp.tsx
  src/components/common/popup/reportPopup/ReportPopUp.tsx
  src/components/editProfile/EditProfile.tsx
  src/components/folder/Folder.tsx
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/keyword/skill/SkillList.tsx
  src/components/list/content/Content.tsx
  src/components/report/comment/Comment.tsx
  src/components/report/skill/Skill.tsx
Labels: ✨ feature, 🛠 refactor, 🐰 YEONA
