Repository KUSITMS-MOAMOA/MOAMOA_FE, pull requests merged in 2025-02, with the labels that each got.

#203 [feat] : Google Analytics 삽입
  package-lock.json
  package.json
  src/App.tsx
Labels: ✨ feature, 🐣 YUMIN

#206 [fix] : OAuth 카카오 로그인 URL 수정
  src/pages/oauthPage/OauthPage.tsx
Labels: 🔨 fix, 🐣 YUMIN

#204 #202 [feat] : google analytics 삽입
  package-lock.json
  package.json
  src/App.tsx
  src/pages/oauthPage/OauthPage.tsx
Labels: ✨ feature, 🐣 YUMIN

#207 [feat] : react-ga4 적용
  package-lock.json
  package.json
  src/App.tsx
  src/utils/ga.ts
Labels: ✨ feature, 🐣 YUMIN

#208 #202 [feat] : react-ga4 적용
  package-lock.json
  package.json
  src/App.tsx
  src/utils/ga.ts
Labels: ✨ feature, 🐣 YUMIN

#209 [feat] : 디자인 수정 사항 반영
  src/components/home/content/Content.Style.ts
  src/components/home/header/Header.Style.ts
  src/components/layout/tabBar/TabBar.Style.ts
  src/components/layout/tabBar/TabBar.tsx
  src/pages/chatPage/ChatPage.tsx
Labels: 💄 ui, 🐰 YEONA

#210 [feat] : 디자인 수정 반영 요청
  src/components/home/content/Content.Style.ts
  src/components/home/header/Header.Style.ts
  src/components/layout/tabBar/TabBar.Style.ts
  src/components/layout/tabBar/TabBar.tsx
  src/pages/chatPage/ChatPage.tsx
Labels: 💄 ui, 🐰 YEONA

#212 [feat] : PWA 적용
  index.html
  package-lock.json
  package.json
  public/icon/Favicon.png
  public/icon/Moamoa-128x128.png
  public/icon/Moamoa-144x144.png
  public/icon/Moamoa-152x152.png
  public/icon/Moamoa-192x192.png
  public/icon/Moamoa-256x256.png
  public/icon/Moamoa-512x512.png
  public/icon/apple-touch-icon-120x120.png
  public/icon/apple-touch-icon-144x144.png
  public/icon/apple-touch-icon-152x152.png
  public/icon/apple-touch-icon-180x180.png
  public/icon/apple-touch-icon-76x76.png
  public/manifest.json
  service-worker.js
  src/main.tsx
  tsconfig.app.json
  vercel.json
  vite.config.ts
Labels: ✨ feature, 🐣 YUMIN

#214 [feat] : PWA 적용
  index.html
  package-lock.json
  package.json
  public/icon/Favicon.png
  public/icon/Moamoa-128x128.png
  public/icon/Moamoa-144x144.png
  public/icon/Moamoa-152x152.png
  public/icon/Moamoa-192x192.png
  public/icon/Moamoa-256x256.png
  public/icon/Moamoa-512x512.png
  public/icon/apple-touch-icon-120x120.png
  public/icon/apple-touch-icon-144x144.png
  public/icon/apple-touch-icon-152x152.png
  public/icon/apple-touch-icon-180x180.png
  public/icon/apple-touch-icon-76x76.png
  public/manifest.json
  service-worker.js
  src/main.tsx
  tsconfig.app.json
  vercel.json
  vite.config.ts
Labels: ✨ feature, 🐣 YUMIN

#215 [refactor] : service-worker 로직 수정
  public/service-worker.js
  service-worker.js
  src/main.tsx
  src/serviceWorkerRegistration.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🔨 fix, 🛠 refactor, 🐣 YUMIN

#216 [refactor] : service-worker 로직 수정
  public/service-worker.js
  service-worker.js
  src/main.tsx
  src/serviceWorkerRegistration.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🛠 refactor, 🐣 YUMIN

#217 [feat] : 사용자 만족도 조사 기능 구현
  .github/ISSUE_TEMPLATE/issue-템플릿.md
  src/api/Feedback.ts
  src/assets/icons/FeedbackIcon.svg
  src/pages/chatPage/ChatPage.tsx
  src/pages/feedbackPage/DislikeOptionModal.Style.ts
  src/pages/feedbackPage/DislikeOptionModal.tsx
  src/pages/feedbackPage/FeedbackModal.Style.ts
  src/pages/feedbackPage/FeedbackModal.tsx
  src/pages/feedbackPage/SelectDislikeModal.Style.ts
  src/pages/feedbackPage/SelectDislikeModal.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
  src/utils/ga.ts
Labels: ✨ feature, ⚙ api, 💄 ui, 🐣 YUMIN

#218 #213 [feat] : 사용자 만족도 조사 기능 구현
  src/api/Feedback.ts
  src/assets/icons/FeedbackIcon.svg
  src/pages/chatPage/ChatPage.tsx
  src/pages/feedbackPage/DislikeOptionModal.Style.ts
  src/pages/feedbackPage/DislikeOptionModal.tsx
  src/pages/feedbackPage/FeedbackModal.Style.ts
  src/pages/feedbackPage/FeedbackModal.tsx
  src/pages/feedbackPage/SelectDislikeModal.Style.ts
  src/pages/feedbackPage/SelectDislikeModal.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
  src/utils/ga.ts
Labels: ✨ feature, ⚙ api, 💄 ui, 🐣 YUMIN

#220 [feat] : 카드 칩 통일 및 UX 라이팅 변경
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/list/List.Style.ts
  src/components/common/list/List.tsx
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/keyword/keywordList/KeywordList.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/list/content/Content.tsx
  src/types/Analysis.ts
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#221 [feat] : 카드 칩 통일 및 UX 라이팅 변경
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/list/List.Style.ts
  src/components/common/list/List.tsx
  src/components/keyword/header/KeywordHeader.style.ts
  src/components/keyword/header/KeywordHeader.tsx
  src/components/keyword/keywordList/KeywordList.Style.ts
  src/components/keyword/keywordList/KeywordList.tsx
  src/components/keyword/keywordSkill/KeywordSkill.tsx
  src/components/list/content/Content.tsx
  src/types/Analysis.ts
Labels: ✨ feature, 💄 ui, 🐰 YEONA

#222 [fix] : API 응답에서 recordId가 undefined로 나오는 문제 수정
  src/pages/reportPage/ReportPage.tsx
Labels: 🔨 fix, 🐣 YUMIN

#224 [feat] : 카드칩 폴더 수정
  src/components/home/content/Content.tsx
Labels: 🔨 fix, ✨ feature, 🐰 YEONA

#223 [fix] : API 응답에서 recordId가 undefined로 나오는 문제 수정
  src/components/home/content/Content.tsx
  src/pages/reportPage/ReportPage.tsx
Labels: 🔨 fix, 🐣 YUMIN

#225 [feat] : 만족도 조사 기능 구현
  index.html
  src/api/Chat.ts
  src/api/Record.ts
  src/components/chat/ChatBox.tsx
  src/components/home/content/Content.tsx
  src/components/list/content/Content.tsx
  src/pages/chatPage/ChatPage.tsx
  src/pages/feedbackPage/DislikeOptionModal.tsx
  src/pages/feedbackPage/FeedbackModal.tsx
  src/pages/homePage/HomePage.tsx
  src/pages/memoPage/MemoPage.tsx
  src/pages/recordCompletePage/RecordCompletePage.tsx
  src/pages/reportPage/ReportPage.tsx
  src/utils/ga.ts
Labels: ✨ feature, 🐣 YUMIN
